-- Case Study 1: IPL 2025 Player Auction
-- Schema and seed data
-- Run with: psql -U postgres -d sql_case_studies -f case_study_1/schema.sql

DROP SCHEMA IF EXISTS case_study_1 CASCADE;
CREATE SCHEMA case_study_1;
SET search_path = case_study_1;

CREATE TABLE ipl_players (
    player        TEXT,
    price_in_cr   DECIMAL(10, 2),
    type          TEXT,
    acquisition   TEXT,
    role          TEXT,
    team          TEXT
);

INSERT INTO ipl_players (player, price_in_cr, type, acquisition, role, team) VALUES
('Ruturaj Gaikwad', 18, 'Indian (capped)', 'Retained', 'Batter', 'Chennai Super Kings'),
('Ravindra Jadeja', 18, 'Indian (capped)', 'Retained', 'All-rounder', 'Chennai Super Kings'),
('Matheesha Pathirana (Sri Lanka)', 13, 'Overseas(capped)', 'Retained', 'Bowler', 'Chennai Super Kings'),
('Shivam Dube', 12, 'Indian (capped)', 'Retained', 'Batter', 'Chennai Super Kings'),
('MS Dhoni', 4, 'Indian (uncapped)', 'Retained', 'Batter/Wicketkeeper', 'Chennai Super Kings'),
('Devon Conway (New Zealand)', 6.25, 'Overseas (capped)', 'Auction', 'Batter', 'Chennai Super Kings'),
('Rahul Tripathi', 3.4, 'Indian (capped)', 'Auction', 'Batter', 'Chennai Super Kings'),
('Rachin Ravindra (New Zealand)', 4, 'Overseas (capped)', 'RTM', 'All-rounder', 'Chennai Super Kings'),
('Ravichandran Ashwin', 9.75, 'Indian (capped)', 'Auction', 'Bowler', 'Chennai Super Kings'),
('Syed Khaleel Ahmed', 4.8, 'Indian (capped)', 'Auction', 'Bowler', 'Chennai Super Kings'),
('Noor Ahmad (Afghanistan)', 10, 'Overseas (capped)', 'Auction', 'Bowler', 'Chennai Super Kings'),
('Vijay Shankar', 1.2, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Chennai Super Kings'),
('Sam Curran', 2.4, 'Overseas (capped)', 'Auction', 'All-rounder', 'Chennai Super Kings'),
('Shaik Rasheed', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Chennai Super Kings'),
('Anshul Kamboj', 3.4, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Chennai Super Kings'),
('Mukesh Choudhary', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Chennai Super Kings'),
('Deepak Hooda', 1.7, 'India (capped)', 'Auction', 'Batter', 'Chennai Super Kings'),
('Gurjapneet Singh', 2.2, 'India (uncapped)', 'Auction', 'Bowler', 'Chennai Super Kings'),
('Nathan Ellis (Australia)', 1.25, 'Overseas (capped)', 'Auction', 'Bowler', 'Chennai Super Kings'),
('Ramakrishna Ghosh', 0.3, 'India (uncapped)', 'Auction', 'All-rounder', 'Chennai Super Kings'),
('Kamlesh Nagarkoti', 0.3, 'India (uncapped)', 'Auction', 'Bowler', 'Chennai Super Kings'),
('Jamie Overton', 1.5, 'Overseas (capped)', 'Auction', 'All-rounder', 'Chennai Super Kings'),
('Shreyas Gopal', 0.3, 'India (uncapped)', 'Auction', 'Bowler', 'Chennai Super Kings'),
('Vansh Bedi', 0.55, 'India (uncapped)', 'Auction', 'Batter', 'Chennai Super Kings'),
('C Andre Siddarth', 0.3, 'India (uncapped)', 'Auction', 'Batter', 'Chennai Super Kings'),
('Axar Patel', 16.5, 'Indian (capped)', 'Retained', 'Bowler', 'Delhi Capitals'),
('Kuldeep Yadav', 13.25, 'Indian (capped)', 'Retained', 'Bowler', 'Delhi Capitals'),
('Tristan Stubbs (South Africa)', 10, 'Overseas (capped)', 'Retained', 'Batter', 'Delhi Capitals'),
('Abishek Porel', 4, 'Indian (uncapped)', 'Retained', 'Batter/Wicketkeeper', 'Delhi Capitals'),
('Mitchell Starc (Australia)', 11.75, 'Overseas (capped)', 'Auction', 'Bowler', 'Delhi Capitals'),
('KL Rahul', 14, 'Indian (capped)', 'Auction', 'Batter/Wicketkeeper', 'Delhi Capitals'),
('Harry Brook (England)', 6.25, 'Overseas (capped)', 'Auction', 'Batter', 'Delhi Capitals'),
('Jake Fraser-Mcgurk (Australia)', 9, 'Overseas (capped)', 'RTM', 'Batter', 'Delhi Capitals'),
('T Natarajan', 10.75, 'Indian (capped)', 'Auction', 'Bowler', 'Delhi Capitals'),
('Karun Nair', 0.5, 'Indian (uncapped)', 'Auction', 'Batter', 'Delhi Capitals'),
('Sameer Rizvi', 0.95, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Delhi Capitals'),
('Ashutosh Sharma', 3.8, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Delhi Capitals'),
('Mohit Sharma', 2.2, 'Indian (uncapped)', 'Auction', 'Bowler', 'Delhi Capitals'),
('Faf du Plessis (South Africa)', 2, 'Overseas (capped)', 'Auction', 'Batter', 'Delhi Capitals'),
('Mukesh Kumar', 8, 'Indian (capped)', 'RTM', 'Bowler', 'Delhi Capitals'),
('Darshan Nalkande', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Delhi Capitals'),
('Vipraj Nigam', 0.5, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Delhi Capitals'),
('Dushmantha Chameera (Sri Lanka)', 0.75, 'Overseas (capped)', 'Auction', 'Bowler', 'Delhi Capitals'),
('Donovan Ferreira', 0.75, 'Overseas (capped)', 'Auction', 'Batter', 'Delhi Capitals'),
('Ajay Mandal', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Delhi Capitals'),
('Manvanth Kumar', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Delhi Capitals'),
('Madhav Tiwari', 0.4, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Delhi Capitals'),
('Tripurana Vijay', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Delhi Capitals'),
('Rashid Khan (Afghanistan)', 18, 'Overseas (capped)', 'Retained', 'Bowler', 'Gujarat Titans'),
('Shubman Gill', 16.5, 'Indian (capped)', 'Retained', 'Batter', 'Gujarat Titans'),
('Sai Sudharsan', 8.5, 'Indian (capped)', 'Retained', 'Batter', 'Gujarat Titans'),
('Rahul Tewatia', 4, 'Indian (uncapped)', 'Retained', 'All-rounder', 'Gujarat Titans'),
('Shahrukh Khan', 4, 'Indian (uncapped)', 'Retained', 'Batter', 'Gujarat Titans'),
('Kagiso Rabada (South Africa)', 10.75, 'Overseas (capped)', 'Auction', 'Bowler', 'Gujarat Titans'),
('Jos Buttler (England)', 15.75, 'Overseas (capped)', 'Auction', 'Batter', 'Gujarat Titans'),
('Mohammad Siraj', 12.25, 'Indian (capped)', 'Auction', 'Batter', 'Gujarat Titans'),
('Prasidh Krishna', 9.5, 'Indian (capped)', 'Auction', 'Bowler', 'Gujarat Titans'),
('Nishant Sindhu', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Gujarat Titans'),
('Mahipal Lomror', 1.7, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Gujarat Titans'),
('Kumar Kushagra', 0.65, 'Indian (uncapped)', 'Auction', 'Batter/Wicketkeeper', 'Gujarat Titans'),
('Anuj Rawat', 0.3, 'Indian (uncapped)', 'Auction', 'Batter/Wicketkeeper', 'Gujarat Titans'),
('Manav Suthar', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Gujarat Titans'),
('Washington Sundar', 3.2, 'Indian (capped)', 'Auction', 'All-rounder', 'Gujarat Titans'),
('Gerald Coetzee (South Africa)', 2.4, 'Overseas (capped)', 'Auction', 'Bowler', 'Gujarat Titans'),
('Arshad Khan', 1.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Gujarat Titans'),
('Gurnoor Brar', 1.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Gujarat Titans'),
('Sherfane Rutherford (West Indies)', 2.6, 'Overseas (capped)', 'Auction', 'Batter', 'Gujarat Titans'),
('R Sai Kishore', 2, 'Indian (capped)', 'RTM', 'All-rounder', 'Gujarat Titans'),
('Ishant Sharma', 0.75, 'Indian (capped)', 'Auction', 'Bowler', 'Gujarat Titans'),
('Jayant Yadav', 0.75, 'Indian (capped)', 'Auction', 'All-rounder', 'Gujarat Titans'),
('Glenn Phillips (New Zealand)', 2, 'Overseas (capped)', 'Auction', 'All-rounder', 'Gujarat Titans'),
('Karim Janat (Afghanistan)', 0.75, 'Overseas (capped)', 'Auction', 'All-rounder', 'Gujarat Titans'),
('Kulwant Khejroliya', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Gujarat Titans'),
('Rinku Singh', 13, 'Indian (capped)', 'Retained', 'Batter', 'Kolkata Knight Riders'),
('Varun Chakaravarthy', 12, 'Indian (capped)', 'Retained', 'Bowler', 'Kolkata Knight Riders'),
('Sunil Narine (West Indies)', 12, 'Overseas (capped)', 'Retained', 'All-rounder', 'Kolkata Knight Riders'),
('Andre Russell (West Indies)', 12, 'Overseas (capped)', 'Retained', 'All-rounder', 'Kolkata Knight Riders'),
('Harshit Rana', 4, 'Indian (uncapped)', 'Retained', 'Bowler', 'Kolkata Knight Riders'),
('Ramandeep Singh', 4, 'Indian (uncapped)', 'Retained', 'Batter', 'Kolkata Knight Riders'),
('Venkatesh Iyer', 23.75, 'Indian (capped)', 'Auction', 'Batter', 'Kolkata Knight Riders'),
('Quinton de Kock (South Africa)', 3.6, 'Overseas (capped)', 'Auction', 'Batter/Wicketkeeper', 'Kolkata Knight Riders'),
('Rahmanullah Gurbaz (Afghanistan)', 2, 'Overseas (capped)', 'Auction', 'Batter/Wicketkeeper', 'Kolkata Knight Riders'),
('Anrich Nortje (South Africa)', 6.5, 'Overseas (capped)', 'Auction', 'Bowler', 'Kolkata Knight Riders'),
('Angkrish Raghuvanshi', 3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Kolkata Knight Riders'),
('Vaibhav Arora', 1.8, 'Indian (uncapped)', 'Auction', 'Bowler', 'Kolkata Knight Riders'),
('Mayank Markande', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Kolkata Knight Riders'),
('Rovman Powell (West Indies)', 1.5, 'Overseas (capped)', 'Auction', 'Batter', 'Kolkata Knight Riders'),
('Manish Pandey', 0.75, 'Indian (capped)', 'Auction', 'Batter', 'Kolkata Knight Riders'),
('Spencer Johnson (Australia)', 2.8, 'Overseas (capped)', 'Auction', 'Bowler', 'Kolkata Knight Riders'),
('Luvnith Sisodia', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Kolkata Knight Riders'),
('Ajinkya Rahane', 1.5, 'Indian (capped)', 'Auction', 'Batter', 'Kolkata Knight Riders'),
('Anukul Roy', 0.4, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Kolkata Knight Riders'),
('Moeen Ali (England)', 2, 'Overseas (capped)', 'Auction', 'All-rounder', 'Kolkata Knight Riders'),
('Umran Malik', 0.75, 'Indian (capped)', 'Auction', 'Bowler', 'Kolkata Knight Riders'),
('Nicholas Pooran (West Indies)', 21, 'Overseas (capped)', 'Retained', 'Batter/Wicketkeeper', 'Lucknow Super Giants'),
('Ravi Bishnoi', 11, 'Indian (capped)', 'Retained', 'Bowler', 'Lucknow Super Giants'),
('Mayank Yadav', 11, 'Indian (capped)', 'Retained', 'Bowler', 'Lucknow Super Giants'),
('Mohsin Khan', 4, 'Indian (uncapped)', 'Retained', 'Bowler', 'Lucknow Super Giants'),
('Ayush Badoni', 4, 'Indian (uncapped)', 'Retained', 'Batter', 'Lucknow Super Giants'),
('Rishabh Pant', 27, 'Indian (capped)', 'Auction', 'Batter/Wicketkeeper', 'Lucknow Super Giants'),
('David Miller (South Africa)', 7.5, 'Overseas (capped)', 'Auction', 'Batter', 'Lucknow Super Giants'),
('Mitchell Marsh (Australia)', 3.4, 'Overseas (capped)', 'Auction', 'All-rounder', 'Lucknow Super Giants'),
('Aiden Markram (South Africa)', 2, 'Overseas (capped)', 'Auction', 'Batter', 'Lucknow Super Giants'),
('Avesh Khan', 9.75, 'Indian (capped)', 'Auction', 'Bowler', 'Lucknow Super Giants'),
('Abdul Samad', 4.2, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Lucknow Super Giants'),
('Aryan Juyal', 0.3, 'Indian (uncapped)', 'Auction', 'Batter/Wicketkeeper', 'Lucknow Super Giants'),
('Akash Deep', 8, 'Indian (capped)', 'Auction', 'Bowler', 'Lucknow Super Giants'),
('Himmat Singh', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Lucknow Super Giants'),
('M Siddharth', 0.75, 'Indian (uncapped)', 'Auction', 'Bowler', 'Lucknow Super Giants'),
('Digvesh Singh', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Lucknow Super Giants'),
('Shahbaz Ahmed', 2.4, 'Indian (capped)', 'Auction', 'All-rounder', 'Lucknow Super Giants'),
('Akash Singh', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Lucknow Super Giants'),
('Shamar Joseph (West Indies)', 0.75, 'Overseas (capped)', 'Auction', 'Bowler', 'Lucknow Super Giants'),
('Prince Yadav', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Lucknow Super Giants'),
('Yuvraj Chaudhary', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Lucknow Super Giants'),
('Rajvardhan Hangargekar', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Lucknow Super Giants'),
('Arshin Kulkarni', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Lucknow Super Giants'),
('Matthew Breetzke', 0.75, 'Overseas (capped)', 'Auction', 'Batter', 'Lucknow Super Giants'),
('Jasprit Bumrah', 18, 'Indian (capped)', 'Retained', 'Bowler', 'Mumbai Indians'),
('Suryakumar Yadav', 16.35, 'Indian (capped)', 'Retained', 'Batter', 'Mumbai Indians'),
('Hardik Pandya', 16.35, 'Indian (capped)', 'Retained', 'All-rounder', 'Mumbai Indians'),
('Rohit Sharma', 16.3, 'Indian (capped)', 'Retained', 'Batter', 'Mumbai Indians'),
('Tilak Varma', 8, 'Indian (capped)', 'Retained', 'Batter', 'Mumbai Indians'),
('Trent Boult (New Zealand)', 12.5, 'Overseas (capped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Naman Dhir', 5.25, 'Indian (uncapped)', 'RTM', 'All-rounder', 'Mumbai Indians'),
('Robin Minz', 0.65, 'Indian (uncapped)', 'Auction', 'Batter/Wicketkeeper', 'Mumbai Indians'),
('Karn Sharma', 0.5, 'Indian (uncapped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Ryan Rickelton (South Africa)', 1, 'Overseas (capped)', 'Auction', 'Batter', 'Mumbai Indians'),
('Deepak Chahar', 9.25, 'Indian (capped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Allah Ghazanfar (Afghanistan)', 4.8, 'Overseas (capped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Will Jacks (England)', 5.25, 'Overseas (capped)', 'Auction', 'All-rounder', 'Mumbai Indians'),
('Ashwani Kumar', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Mitchell Santner (New Zealand)', 2, 'Overseas (capped)', 'Auction', 'All-rounder', 'Mumbai Indians'),
('Reece Topley (England)', 0.75, 'Overseas (capped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Shrijith Krishnan', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Raj Bawa', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Mumbai Indians'),
('Satyanarayana Raju', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Bevon Jacobs (New Zealad)', 0.3, 'Overseas (uncapped)', 'Auction', 'Batter', 'Mumbai Indians'),
('Arjun Tendulkar', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Lizaad Williams (South Africa)', 0.75, 'Overseas (capped)', 'Auction', 'Bowler', 'Mumbai Indians'),
('Vignesh Puthur', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Mumbai Indians'),
('Shashank Singh', 5.5, 'Indian (uncapped)', 'Retained', 'Batter', 'Punjab Kings'),
('Prabhsimran Singh', 4, 'Indian (uncapped)', 'Retained', 'Batter', 'Punjab Kings'),
('Arshdeep Singh', 18, 'Indian (capped)', 'RTM', 'Bowler', 'Punjab Kings'),
('Shreyas Iyer', 26.75, 'Indian (capped)', 'Auction', 'Batter/Wicketkeeper', 'Punjab Kings'),
('Yuzvendra Chahal', 18, 'Indian (capped)', 'Auction', 'Bowler', 'Punjab Kings'),
('Marcus Stoinis (Australia)', 11, 'Overseas (capped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Glenn Maxwell (Australia)', 4.2, 'Overseas (capped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Nehal Wadhera', 4.2, 'Indian (uncapped)', 'Auction', 'Batter', 'Punjab Kings'),
('Harpreet Brar', 1.5, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Vishnu Vinod', 0.95, 'Indian (uncapped)', 'Auction', 'Batter/Wicketkeeper', 'Punjab Kings'),
('Vijaykumar Vyshak', 1.8, 'Indian (uncapped)', 'Auction', 'Bowler', 'Punjab Kings'),
('Yash Thakur', 1.6, 'Indian (uncapped)', 'Auction', 'Bowler', 'Punjab Kings'),
('Marco Jansen (South Africa)', 7, 'Overseas (capped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Josh Inglis (Australia)', 2.6, 'Overseas (capped)', 'Auction', 'Batter', 'Punjab Kings'),
('Lockie Ferguson (New Zealand)', 2, 'Overseas (capped)', 'Auction', 'Bowler', 'Punjab Kings'),
('Azmatullah Omarzai (Afghanistan)', 2.4, 'Overseas (capped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Harnoor Pannu', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Punjab Kings'),
('Kuldeep Sen', 0.8, 'Indian (capped)', 'Auction', 'Bowler', 'Punjab Kings'),
('Priyansh Arya', 3.8, 'Indian (uncapped)', 'Auction', 'Batter', 'Punjab Kings'),
('Aaron Hardie (Australia)', 1.25, 'Overseas (capped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Suryash Shedge', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Musheer Khan', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Xavier Bartlett', 0.8, 'Overseas (capped)', 'Auction', 'Bowler', 'Punjab Kings'),
('Pyla Avinash', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Punjab Kings'),
('Praveen Dubey', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Punjab Kings'),
('Sanju Samson', 18, 'Indian (capped)', 'Retained', 'Batter/Wicketkeeper', 'Rajasthan Royals'),
('Yashasvi Jaiswal', 18, 'Indian (capped)', 'Retained', 'Batter', 'Rajasthan Royals'),
('Riyan Parag', 14, 'Indian (capped)', 'Retained', 'Batter', 'Rajasthan Royals'),
('Dhruv Jurel', 14, 'Indian (capped)', 'Retained', 'Batter/Wicketkeeper', 'Rajasthan Royals'),
('Shimron Hetmyer (West Indies)', 11, 'Overseas (capped)', 'Retained', 'Batter', 'Rajasthan Royals'),
('Sandeep Sharma', 4, 'Indian (uncapped)', 'Retained', 'Bowler', 'Rajasthan Royals'),
('Jofra Archer (England)', 12.5, 'Overseas (capped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Mahesh Theekshana (Sri Lanka)', 4.4, 'Overseas (capped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Wanindu Hasaranga (Sri Lanka)', 5.25, 'Overseas (capped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Akash Madhwal', 1.2, 'Indian (uncapped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Kumar Kartikeya Singh', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Nitish Rana', 4.2, 'Indian (capped)', 'Auction', 'All-rounder', 'Rajasthan Royals'),
('Tushar Deshpande', 6.5, 'Indian (capped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Shubham Dubey', 0.8, 'Indian (uncapped)', 'Auction', 'Batter', 'Rajasthan Royals'),
('Yudhvir Charak', 0.35, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Rajasthan Royals'),
('Fazalhaq Farooqi', 2, 'Overseas (capped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Vaibhav Suryavanshi', 1.1, 'Indian (uncapped)', 'Auction', 'Batter', 'Rajasthan Royals'),
('Kwena Maphaka (South Africa)', 0.75, 'Overseas (capped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Ashok Sharma', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Rajasthan Royals'),
('Kunal Singh Rathore', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Rajasthan Royals'),
('Virat Kohli', 21, 'Indian (capped)', 'Retained', 'Batter', 'Royal Challengers Bengaluru'),
('Rajat Patidar', 11, 'Indian (capped)', 'Retained', 'Batter', 'Royal Challengers Bengaluru'),
('Yash Dayal', 5, 'Indian (uncapped)', 'Retained', 'Bowler', 'Royal Challengers Bengaluru'),
('Liam Livingstone (England)', 8.75, 'Overseas (capped)', 'Auction', 'All-rounder', 'Royal Challengers Bengaluru'),
('Phil Salt (England)', 11.5, 'Overseas (capped)', 'Auction', 'Batter/Wicketkeeper', 'Royal Challengers Bengaluru'),
('Jitesh Sharma', 11, 'Indian (capped)', 'Auction', 'Batter', 'Royal Challengers Bengaluru'),
('Josh Hazlewood (Australia)', 12.5, 'Overseas (capped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Rasikh Dar', 6, 'Indian (uncapped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Suyash Sharma', 2.6, 'Indian (uncapped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Krunal Pandya', 5.75, 'Indian (capped)', 'Auction', 'All-rounder', 'Royal Challengers Bengaluru'),
('Bhuvneshwar Kumar', 10.75, 'Indian (capped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Swapnil Singh', 0.5, 'Indian (uncapped)', 'RTM', 'All-rounder', 'Royal Challengers Bengaluru'),
('Tim David (Australia)', 3, 'Overseas (capped)', 'Auction', 'All-rounder', 'Royal Challengers Bengaluru'),
('Romario Shepherd (West Indies)', 1.5, 'Overseas (capped)', 'Auction', 'All-rounder', 'Royal Challengers Bengaluru'),
('Nuwan Thushara (Sri Lanka)', 1.6, 'Overseas (capped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Manoj Bhandage', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Jacob Bethell (England)', 2.6, 'Overseas (capped)', 'Auction', 'All-rounder', 'Royal Challengers Bengaluru'),
('Devdutt Padikkal', 2, 'Indian (capped)', 'Auction', 'Batter', 'Royal Challengers Bengaluru'),
('Swastik Chikara', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Royal Challengers Bengaluru'),
('Mohit Rathee', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Abhinandan Singh', 0.3, 'Indian (uncapped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Lungi Ngidi', 1, 'Overseas (capped)', 'Auction', 'Bowler', 'Royal Challengers Bengaluru'),
('Heinrich Klaasen (South Africa)', 23, 'Overseas (capped)', 'Retained', 'Batter', 'Sunrisers Hyderabad'),
('Pat Cummins (Australia)', 18, 'Overseas (capped)', 'Retained', 'Bowler', 'Sunrisers Hyderabad'),
('Abhishek Sharma', 14, 'Indian (capped)', 'Retained', 'All-rounder', 'Sunrisers Hyderabad'),
('Travis Head (Australia)', 14, 'Overseas (capped)', 'Retained', 'Batter', 'Sunrisers Hyderabad'),
('Nitish Kumar Reddy', 6, 'Indian (capped)', 'Retained', 'All-rounder', 'Sunrisers Hyderabad'),
('Mohammad Shami', 10, 'Indian (capped)', 'Auction', 'Bowler', 'Sunrisers Hyderabad'),
('Harshal Patel', 8, 'Indian (capped)', 'Auction', 'All-rounder', 'Sunrisers Hyderabad'),
('Ishan Kishan', 11.25, 'Indian (capped)', 'Auction', 'Batter/Wicketkeeper', 'Sunrisers Hyderabad'),
('Rahul Chahar', 3.2, 'Indian (capped)', 'Auction', 'Bowler', 'Sunrisers Hyderabad'),
('Adam Zampa (Australia)', 2.4, 'Overseas (capped)', 'Auction', 'Bowler', 'Sunrisers Hyderabad'),
('Atharva Taide', 0.3, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Sunrisers Hyderabad'),
('Abhinav Manohar', 3.2, 'Indian (uncapped)', 'Auction', 'All-rounder', 'Sunrisers Hyderabad'),
('Simarjeet Singh', 1.5, 'Indian (uncapped)', 'Auction', 'Bowler', 'Sunrisers Hyderabad'),
('Zeeshan Ansari', 0.4, 'Indian (uncapped)', 'Auction', 'Bowler', 'Sunrisers Hyderabad'),
('Jaydev Unadkat', 1, 'Indian (capped)', 'Auction', 'Bowler', 'Sunrisers Hyderabad'),
('Brydon Carse (England)', 1, 'Overseas (capped)', 'Auction', 'All-rounder', 'Sunrisers Hyderabad'),
('Kamindu Mendis (Sri Lanka)', 0.75, 'Overseas (capped)', 'Auction', 'All-rounder', 'Sunrisers Hyderabad'),
('Aniket Verma', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Sunrisers Hyderabad'),
('Eshan Malinga (Sri Lanka)', 1.2, 'Overseas (uncapped)', 'Auction', 'Bowler', 'Sunrisers Hyderabad'),
('Sachin Baby', 0.3, 'Indian (uncapped)', 'Auction', 'Batter', 'Sunrisers Hyderabad');
